name: 🐛 Bug report
description: File a bug report
labels: ["bug"]
assignees:
  - Bhupesh-V
body:
  - type: markdown
    attributes:
      value: |
        "Thanks for taking the time to fill this bug report!"
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Please explain in detail the bug that you see & what did you expect. Include a screenshot (in GIF formats preferably) if possible.
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: shell_type
    attributes:
      label: What shell are you using in your script?
      description: Please share the shell type you are using in your script. E.g. bash, sh, zsh, etc.
      render: bash
    validations:
      required: true
  - type: textarea
    id: shell_script
    attributes:
      label: Can you share the shell script that you are using?
      description: Please link to the shell script you are facing problems with or copy-paste some code.
      render: bash
  - type: dropdown
    id: browsers
    attributes:
      label: What OS are you seeing the problem on?
      multiple: false
      options:
        - Linux Based
        - MacOS
        - Windows
    validations:
      required: true
  - type: textarea
    id: docker_version
    attributes:
      label: Please share the version of Docker you are using.
      description: Use command "docker version" to get this.
    validations:
      required: true